[package]
name = "paseto-v3"
version = "0.1.0"
edition = "2024"

[dependencies]
paseto-core.workspace = true

p384 = { version = "0.13.0", features = ["ecdh", "pkcs8", "ecdsa-core"] }
aws-lc-rs = "1.14"

[dev-dependencies]
paseto-json.workspace = true

hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libtest-mimic = "0.8.1"

[[test]]
name = "paseto-test-vectors"
path = "tests/paseto.rs"
harness = false
