[package]
name = "paseto-v3"
version = "0.1.0"
edition = "2024"

[dependencies]
paseto-core.workspace = true

generic-array = "0.14"
cipher = "0.4"
digest = { version = "0.10", features = ["mac"] }
rand = "0.9"

aes = { version = "0.8.2" }
ctr = { version = "0.9.2" }
hmac = { version = "0.12.1" }
sha2 = { version = "0.10.2" }
p384 = { version = "0.13.0", features = ["ecdh", "pkcs8", "ecdsa-core"] }
hkdf = { version = "0.12.3" }
pbkdf2 = { version = "0.12.1" }

[dev-dependencies]
paseto-json.workspace = true

hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libtest-mimic = "0.8.1"

[[test]]
name = "paseto-test-vectors"
path = "tests/paseto.rs"
harness = false
