[package]
name = "paseto-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
serde = ["dep:serde_core"]

[dependencies]
serde_core = { version = "1", optional = true }

base64ct = { version = "1.6.0", features = ["alloc"] }
rand_core = "0.9"
